### ISSUE TITLE
Cannot install bionic legs in Warg

### ISSUE THREAD

**Issue by KittenRaee** [emipa606/XNDVanillaFriendlyAnimalSurgery#1]
Bionic legs of any size are unable to be installed on warg. 

![image](https://user-images.githubusercontent.com/23376922/128700733-668a1cdc-bc5e-4ba2-be72-e40e269d6058.png)

**Comment by KittenRaee** [comment]
[Warg test.txt](https://github.com/emipa606/XNDVanillaFriendlyAnimalSurgery/files/6954177/Warg.test.txt)
Test save file (extension type changed because Github)

**Comment by emipa606** [comment]
Good catch, seems I missed the bionic legs in the code. Should be fixed now!
